version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbit-mq
    ports:
      - "5672:5672"  # RabbitMQ AMQP port
      - "15672:15672"  # RabbitMQ Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_network

  order-service:
    build:
      context: ./order-service
    ports:
      - "3000:3000"  # Expose Order Service to the host
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_network

  inventory-service:
    build:
      context: ./inventory-service
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_network

  notification-service:
    build:
      context: ./notification-service
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_network

  payment-service:
    build:
      context: ./payment-service
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_network

volumes:
  rabbitmq_data:

networks:
  rabbitmq_network:
    driver: bridge